## Python Dates and Times

In [2]:
import datetime as dt
import time as tm

In [11]:


sec = 2**32
sec

dt.datetime.fromtimestamp(sec)

# tm.time() - sec

datetime.datetime(2106, 2, 7, 6, 28, 16)

## Advanced Python Objects, map()

In [10]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

# def split_title_and_name(person):
#     return people.split(' ')[0] + people.split(' ')[-1]

# list(map(split_title_and_name,people))

def remove_first_name(person):
    return person.split(' ')[0] + ' ' + person.split(' ')[-1]

a = list(map(remove_first_name, people))

b = [person.split(' ')[0] + ' ' + person.split(' ')[-1] for person in people]

In [11]:
a==b

True

In [25]:
# Anonymous Functions
# lambdas are ways of creating functions without a name. everthing before the colon are the inputs and after the colon is what you are doing with those inputs. no default values for lambdas.
my_function = lambda a, b, c : a + b

In [26]:
my_function(1, 2, 3)

3

In [27]:

(lambda a, b, c : a + b)(1, 2, 3)

3

In [28]:
my_list = []
for number in range(0, 1000):
    if number % 2 == 0:
        my_list.append(number)

In [29]:
my_list

lowercase = "abcdefghijklmnopqrstuvwxyz"
digits = "0123456789"

every_combo = [a + b + c + d for a in lowercase for b in lowercase for c in digits for d in digits]
every_combo[-1]

'zz99'

In [31]:
import numpy as np
import math

## Array Creation

In [72]:
a = np.array([1, 2, 3])
print(a)
print(a.ndim)

[1 2 3]
1


In [73]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(b.ndim)
print(b.shape)
print(b.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
int64


In [74]:
np.random.rand(2, 3)

array([[0.56539905, 0.25753487, 0.02929989],
       [0.22019103, 0.16693641, 0.84899388]])

In [75]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [76]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [77]:
np.arange(1, 50.1, 1)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [78]:
np.linspace(1, 50)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [79]:
np.arange(0, 100, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [80]:
numbers = np.linspace(0, 100, 21)
numbers

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

## Array Operations

In [81]:
numbers > 15

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [82]:
print(numbers.mean())
print(numbers.sum())
print(numbers.max())

50.0
1050.0
100.0


In [83]:
matrix = numbers.reshape(3, 7)
matrix.sum()

np.float64(1050.0)

In [84]:
from PIL import Image
from IPython.display import display

im = Image.open('chris.tiff')

FileNotFoundError: [Errno 2] No such file or directory: 'chris.tiff'

## Indexing, Slicing and Iterating

In [89]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [86]:
b = np.full(a.shape, 3)
b

array([[3, 3],
       [3, 3],
       [3, 3]])

In [87]:
a>b

array([[False, False],
       [False,  True],
       [ True,  True]])

In [90]:
a>3

array([[False, False],
       [False,  True],
       [ True,  True]])

In [91]:
a[a>b] == a[a>3]

array([ True,  True,  True])

In [92]:
a_slice = np.array([0,1,2,3,4,5])
print(a_slice[:3])

[0 1 2]


In [93]:
a_slice = np.array([[1,2,3,4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a_slice[:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [94]:
a_slice[:2, 0] # This is a view to the original array, changing this value changes the underlying array

array([1, 5])

## Trying Numpy with Datasets

In [95]:
wines = np.genfromtxt("data/winequality-red.csv", delimiter=";", skip_header=1)

In [96]:
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]],
      shape=(1599, 12))

In [97]:
wines[:, 0]

array([7.4, 7.8, 7.8, ..., 6.3, 5.9, 6. ], shape=(1599,))

In [98]:
wines[:, 0:1]

array([[7.4],
       [7.8],
       [7.8],
       ...,
       [6.3],
       [5.9],
       [6. ]], shape=(1599, 1))

This is another great example of how the shape of the data is an abstraction which we can layer intentionally on top of the data we are working with.

In [99]:
wines[:, 0:3]

array([[7.4  , 0.7  , 0.   ],
       [7.8  , 0.88 , 0.   ],
       [7.8  , 0.76 , 0.04 ],
       ...,
       [6.3  , 0.51 , 0.13 ],
       [5.9  , 0.645, 0.12 ],
       [6.   , 0.31 , 0.47 ]], shape=(1599, 3))

In [100]:
wines[:,  [0, 2, 4]]

array([[7.4  , 0.   , 0.076],
       [7.8  , 0.   , 0.098],
       [7.8  , 0.04 , 0.092],
       ...,
       [6.3  , 0.13 , 0.076],
       [5.9  , 0.12 , 0.075],
       [6.   , 0.47 , 0.067]], shape=(1599, 3))

In [101]:
wines[:, -1].mean()



np.float64(5.6360225140712945)

In [102]:
graduate_admission = np.genfromtxt('data/Admission_Predict.csv', dtype=None, delimiter=',', skip_header=1, names=['Serial No', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR', 'CGPA', 'Research', 'Chance of Admit'])

graduate_admission['Serial_No']

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [103]:
graduate_admission.shape

(400,)

In [104]:
graduate_admission[:5, 'CGPA']

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [105]:
graduate_admission['CGPA'][0:5]

array([9.65, 8.87, 8.  , 8.67, 8.21])

## Regular Expressions

import re

In [106]:
import re

In [161]:
text = "This is a good day."

# Checking for an example

if re.search("good", text):
    print("Wonderful!")
else:
    print("Alas :(")

Wonderful!


In [162]:
re.search("good", text)

<re.Match object; span=(10, 14), match='good'>

In addition to checking for conditionals, we can segment a string. The work that regex does here is called tokenizing, where the string is separated into substrings based on patterns. Tokenizing is a core activity in natural language processing.

The findall() and split() functions will parse the string for us and return chunks.

In [15]:
text = "Amy works diligently. Amy gets good grades. Our student Amy is successful."

re.split("Amy", text)

['',
 ' works diligently. ',
 ' gets good grades. Our student ',
 ' is successful.']

In [16]:
re.findall("Amy", text)

['Amy', 'Amy', 'Amy']

In [20]:
re.search("Amy", text)

<re.Match object; span=(0, 3), match='Amy'>

## Patterns and Character Classes

In [39]:
grades = "ACAAAABCBCBAA"

In [159]:

print(re.findall("AC", grades)) # All AC in the string
print(re.findall("[AC]", grades)) # All As or Cs in the string
print(re.findall("[A-C]", grades)) # All As through Cs in the string
print(re.findall("AB|C", grades)) # All As or Cs in the string

print(re.findall("[^A]", grades)) # Not A
print(re.findall("^[A]", grades)) # A at the start of the string


['AC']
['A', 'C', 'A', 'A', 'A', 'A', 'C', 'C', 'A', 'A']
['A', 'C', 'A', 'A', 'A', 'A', 'B', 'C', 'B', 'C', 'B', 'A', 'A']
['C', 'AB', 'C', 'C']
['C', 'B', 'C', 'B', 'C', 'B']
['A']


In [41]:
## Quantifiers

In [150]:
import re
s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
result

['A', 'AA', 'AA', 'AA', 'A']

In [43]:
[(]\d{3}[)]\s\d{3}[-]\d{4}re.findall("A{2,10}", grades)

['AAAA', 'AA']

In [50]:
re.findall("A{1,1}A{1,1}", grades)

['AA', 'AA', 'AA']

In [51]:
def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result

In [54]:
import numpy as np

In [59]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [60]:
l2_dist(a, b)

np.float64(8.0)

In [67]:
np.reshape(a, (4, ))

array([1, 2, 3, 4])

In [68]:
np.reshape(a, (2 * 2))

array([1, 2, 3, 4])

In [70]:
np.reshape(a, (2 * 2, 1))

array([[1],
       [2],
       [3],
       [4]])

In [71]:
import numpy as np

old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0

print(old)

[[0 0 1]
 [1 1 1]]


In [113]:
new[:, :]

array([[0, 0, 1],
       [1, 1, 1]])

In [117]:
matrix = np.ones((4, 4))

In [125]:
matrix[2, :]

array([2., 2., 2., 2.])

In [123]:
matrix[2][:] = 2

In [127]:
matrix[:, 2] = 3

In [128]:
matrix

array([[1., 1., 3., 1.],
       [1., 1., 3., 1.],
       [2., 2., 3., 2.],
       [1., 1., 3., 1.]])

In [129]:
import re
s = 'ACBCAC'

In [138]:
re.findall('^[A|C]', s)

['A']

In [139]:
re.findall('^[AC]', s)

['A']

In [152]:
text ="Office of Research Administration: (734) 647-6333 | 4325 North Quad"

re.findall("[(]\\d{3}[)]\\s\\d{3}[-]\\d{4}", text)

['(734) 647-6333']

In [158]:
text=r'''Everyone has the following fundamental freedoms:
    (a) freedom of conscience and religion;
    (b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
    (c) freedom of peaceful assembly; and
    (d) freedom of association.'''

import re
pattern = text=r'''Everyone has the following fundamental freedoms:
    (a) freedom of conscience and religion;
    (b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
    (c) freedom of peaceful assembly; and
    (d) freedom of association.'''

import re
print(len(re.findall("\\(.\\)",text)))

4
