In [5]:
import numpy as np

<a name="1"></a>
## 1 - Introduction

<a name="1.1"></a>
### 1.1 - Transformations

A **transformation** is a function from one vector space to another that respects the underlying (linear) structure of each vector space. Referring to a specific transformation, you can use a symbol, such as $T$. Specifying the spaces containing the input and output vectors, e.g. $\mathbb{R}^2$ and $\mathbb{R}^3$, you can write $T: \mathbb{R}^2 \rightarrow \mathbb{R}^3$. Transforming vector $v \in \mathbb{R}^2$ into the vector $w\in\mathbb{R}^3$ by the transformation $T$, you can use the notation $T(v)=w$ and read it as "*T of v equals to w*" or "*vector w is an **image** of vector v with the transformation T*".

The following Python function corresponds to the transformation $T: \mathbb{R}^2 \rightarrow \mathbb{R}^3$ with the following symbolic formula:

$$T\begin{pmatrix}
          \begin{bmatrix}
           v_1 \\
           v_2
          \end{bmatrix}\end{pmatrix}=
          \begin{bmatrix}
           3v_1 \\
           0 \\
           -2v_2
          \end{bmatrix}
          \tag{1}
          $$

In [6]:
def T(v):
    w = np.zeros((3,1))
    w[0,0] = 3*v[0,0]
    w[2,0] = -2*v[1,0]

    return w

v = np.array([[3], [5]])
w = T(v)

print("Original vector:\n", v, "\n\n Result of the transformation:\n", w)

Original vector:
 [[3]
 [5]] 

 Result of the transformation:
 [[  9.]
 [  0.]
 [-10.]]


In [12]:
def new_T(v):
    return np.array([[3*v[0,0]], [0], [-2*v[1,0]]])

v = np.array([[3], [5]])
w = new_T(v)

print("Original vector:\n", v, "\n\n Result of the transformation:\n", w)

Original vector:
 [[3]
 [5]] 

 Result of the transformation:
 [[  9]
 [  0]
 [-10]]


<a name="1.2"></a>
### 1.2 - Linear Transformations

A transformation $T$ is said to be **linear** if the following two properties are true for any scalar $k$, and any input vectors $u$ and $v$:

1. $T(kv)=kT(v)$,
2. $T(u+v)=T(u)+T(v)$.

In the example above $T$ is a linear transformation:

$$T (kv) =
          T \begin{pmatrix}\begin{bmatrix}
          kv_1 \\
          kv_2
          \end{bmatrix}\end{pmatrix} =
          \begin{bmatrix}
           3kv_1 \\
           0 \\
           -2kv_2
          \end{bmatrix} =
          k\begin{bmatrix}
           3v_1 \\
           0 \\
           -2v_2
          \end{bmatrix} =
          kT(v),\tag{2}$$

$$T (u+v) =
          T \begin{pmatrix}\begin{bmatrix}
          u_1 + v_1 \\
          u_2 + v_2
          \end{bmatrix}\end{pmatrix} =
          \begin{bmatrix}
           3(u_1+v_1) \\
           0 \\
           -2(u_2+v_2)
          \end{bmatrix} =
          \begin{bmatrix}
           3u_1 \\
           0 \\
           -2u_2
          \end{bmatrix} +
          \begin{bmatrix}
           3v_1 \\
           0 \\
           -2v_2
          \end{bmatrix} =
          T(u)+T(v).\tag{3}$$

In [14]:
u = np.array([[1], [-2]])
v = np.array([[1], [2]])

k = 0.5

print("T(k*v):\n", T(k*v), "\n k*T(v):\n", k*T(v), "\n\n")
print("T(u+v):\n", T(u+v), "\n\n T(u)+T(v):\n", T(u)+T(v))

T(k*v):
 [[ 1.5]
 [ 0. ]
 [-2. ]] 
 k*T(v):
 [[ 1.5]
 [ 0. ]
 [-2. ]] 


T(u+v):
 [[6.]
 [0.]
 [0.]] 

 T(u)+T(v):
 [[6.]
 [0.]
 [0.]]


In [17]:
def non_linear_T(v):
    return np.array([[v[0,0]**2], [0], [-2*v[1,0]]])

v = np.array([[3], [5]])
w = non_linear_T(v)

print("Original vector:\n", v, "\n\n Result of the transformation:\n", w)

Original vector:
 [[3]
 [5]] 

 Result of the transformation:
 [[  9]
 [  0]
 [-10]]


In [18]:
u = np.array([[1], [-2]])
v = np.array([[1], [2]])

k = 0.5

print("T(k*v):\n", non_linear_T(k*v), "\n k*T(v):\n", k*non_linear_T(v), "\n\n")
print("T(u+v):\n", non_linear_T(u+v), "\n\n T(u)+T(v):\n", non_linear_T(u)+T(v))

T(k*v):
 [[ 0.25]
 [ 0.  ]
 [-2.  ]] 
 k*T(v):
 [[ 0.5]
 [ 0. ]
 [-2. ]] 


T(u+v):
 [[4]
 [0]
 [0]] 

 T(u)+T(v):
 [[4.]
 [0.]
 [0.]]
