## Mismatching lists challenge

## Instructions
- There are two lists: discounts and product prices. The discounts represents fractions of the year, where 4 elements denotes 4 quarters of the year. 
- Product prices has 12 elements - each denoting a product that is going on sale for each month.
- Write a for loop that will multiply each product price by its equivalent discount. For example, the first quarter of product_prices should be multipled by (1-0.25) ie (1 - discounts[0]). 
Then the second quarter of product prices (30, 1000, 105) should be multipled by 1-0.1 ie: (1-discounts[1]).

## Additional constraints
- The number of values in discounts could change. So it might represent quarters, halves, thirds and so on.
- The number of values in discounts will always be less than or equal to the number of values in product_prices
- Your are not to use **if** statements in your code
- AI assistance is not allowed

## Hints
- This problem can be solved by focusing on the ratio between the length of product_prices and discounts
- The index, lengths of lists and fractions will help you.
- This challenge is to be solved using maths not condtional code.

In [114]:
discounts = [0.25, 0.1, (1/3), 0.2]
product_prices = [10, 13, 25, 30, 1000, 105, 35, 75, 100, 200, 20, 5]

import numpy as np

In [115]:
len(discounts)

4

In [116]:
len(product_prices)

12

In [117]:
product_prices[0:int(len(product_prices)/len(discounts))]

groups = int(len(product_prices)/len(discounts))

In [118]:
for quarter in range(len(discounts)):
    print(quarter, quarter+1)
    print(product_prices[quarter*groups:(quarter+1)*groups] - np.array(product_prices[quarter*groups:(quarter+1)*groups])*discounts[quarter])

0 1
[ 7.5   9.75 18.75]
1 2
[ 27.  900.   94.5]
2 3
[23.33333333 50.         66.66666667]
3 4
[160.  16.   4.]


In [121]:
def apply_discount(discount, price):
    return np.array(price) * 1-discount

In [128]:
groups = int(len(product_prices)/len(discounts))
print(groups)


new_prices = [apply_discount(discounts[i], product_prices[i*groups:(i+1)*groups]) for i in range(len(discounts))]

flat_list = [x for xs in new_prices for x in xs]
flat_list


3


[np.float64(9.75),
 np.float64(12.75),
 np.float64(24.75),
 np.float64(29.9),
 np.float64(999.9),
 np.float64(104.9),
 np.float64(34.666666666666664),
 np.float64(74.66666666666667),
 np.float64(99.66666666666667),
 np.float64(199.8),
 np.float64(19.8),
 np.float64(4.8)]

In [72]:
# Segment the list into equal parts
# Apply function to each part of the list
# Concat the list back together

# Use list comprehension

In [86]:
discounts = [0.25, 0.1, (1/3), 0.2]
product_prices = [10, 13, 25, 30, 1000, 105, 35, 75, 100, 200, 20, 5]
items_per_group = len(product_prices) / len(discounts)
print(items_per_group)

3.0


In [87]:
# Not sure how this handles uneven groups
def create_groups(group_size, items)
    return items[0:group_size]

0
1
2


In [88]:
import itertools

In [108]:
a = itertools.batched(product_prices, int(items_per_group))

In [109]:
b = np.array(list(a))

In [110]:
b

array([[  10,   13,   25],
       [  30, 1000,  105],
       [  35,   75,  100],
       [ 200,   20,    5]])

In [132]:
from scipy import stats
from utils import setup_project_root
import pandas as pd

setup_project_root()

WindowsPath('C:/Users/zak/Projects/PycharmProjects/data-science')

In [134]:
life = pd.read_csv('data/Life_Expectancy_Data.csv')

In [138]:
import seaborn as sns

In [153]:
life

array([['Afghanistan', 2015, 'Developing', ..., 17.3, 0.479, 10.1],
       ['Afghanistan', 2014, 'Developing', ..., 17.5, 0.476, 10.0],
       ['Afghanistan', 2013, 'Developing', ..., 17.7, 0.47, 9.9],
       ...,
       ['Zimbabwe', 2002, 'Developing', ..., 1.3, 0.427, 10.0],
       ['Zimbabwe', 2001, 'Developing', ..., 1.7, 0.427, 9.8],
       ['Zimbabwe', 2000, 'Developing', ..., 11.2, 0.434, 9.8]],
      shape=(2938, 22), dtype=object)

In [146]:
life[' BMI ']

0       19.1
1       18.6
2       18.1
3       17.6
4       17.2
        ... 
2933    27.1
2934    26.7
2935    26.3
2936    25.9
2937    25.5
Name:  BMI , Length: 2938, dtype: float64

In [147]:
zip()

## Normalising Data

Looking for variation in the mean.


In [160]:
life

Country  Year      Status  Life expectancy   Adult Mortality  \
0     Afghanistan  2015  Developing              65.0            263.0   
1     Afghanistan  2014  Developing              59.9            271.0   
2     Afghanistan  2013  Developing              59.9            268.0   
3     Afghanistan  2012  Developing              59.5            272.0   
4     Afghanistan  2011  Developing              59.2            275.0   
...           ...   ...         ...               ...              ...   
2933     Zimbabwe  2004  Developing              44.3            723.0   
2934     Zimbabwe  2003  Developing              44.5            715.0   
2935     Zimbabwe  2002  Developing              44.8             73.0   
2936     Zimbabwe  2001  Developing              45.3            686.0   
2937     Zimbabwe  2000  Developing              46.0            665.0   

      infant deaths  Alcohol  percentage expenditure  Hepatitis B  Measles   \
0                62     0.01               71.279624         65.0      1154   
1                64     0.01               73.523582         62.0       492   
2                66     0.01               73.219243         64.0       430   
3                69     0.01               78.184215         67.0      2787   
4                71     0.01                7.097109         68.0      3013   
...             ...      ...                     ...          ...       ...   
2933             27     4.36                0.000000         68.0        31   
2934             26     4.06                0.000000          7.0       998   
2935             25     4.43                0.000000         73.0       304   
2936             25     1.72                0.000000         76.0       529   
2937             24     1.68                0.000000         79.0      1483   

      ...  Polio  Total expenditure  Diphtheria    HIV/AIDS         GDP  \
0     ...    6.0               8.16         65.0        0.1  584.259210   
1     ...   58.0               8.18         62.0        0.1  612.696514   
2     ...   62.0               8.13         64.0        0.1  631.744976   
3     ...   67.0               8.52         67.0        0.1  669.959000   
4     ...   68.0               7.87         68.0        0.1   63.537231   
...   ...    ...                ...          ...        ...         ...   
2933  ...   67.0               7.13         65.0       33.6  454.366654   
2934  ...    7.0               6.52         68.0       36.7  453.351155   
2935  ...   73.0               6.53         71.0       39.8   57.348340   
2936  ...   76.0               6.16         75.0       42.1  548.587312   
2937  ...   78.0               7.10         78.0       43.5  547.358878   

      Population   thinness  1-19 years   thinness 5-9 years  \
0     33736494.0                   17.2                 17.3   
1       327582.0                   17.5                 17.5   
2     31731688.0                   17.7                 17.7   
3      3696958.0                   17.9                 18.0   
4      2978599.0                   18.2                 18.2   
...          ...                    ...                  ...   
2933  12777511.0                    9.4                  9.4   
2934  12633897.0                    9.8                  9.9   
2935    125525.0                    1.2                  1.3   
2936  12366165.0                    1.6                  1.7   
2937  12222251.0                   11.0                 11.2   

      Income composition of resources  Schooling  
0                               0.479       10.1  
1                               0.476       10.0  
2                               0.470        9.9  
3                               0.463        9.8  
4                               0.454        9.5  
...                               ...        ...  
2933                            0.407        9.2  
2934                            0.418        9.5  
2935                            0.427      

## ANOVA and MANOVA

In [150]:
from statsmodels.formula.api import ols
import statsmodels.api as sm

In [157]:
model = ols('Alcohol ~ C(Country)', data=life).fit()
table = sm.stats.anova_lm(model, typ=2)
table

C:\Users\zak\Projects\PycharmProjects\data-science\.venv\Lib\site-packages\statsmodels\base\model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 192, but rank is 190
  warnings.warn('covariance of constraints does not have full '


sum_sq      df           F  PR(>F)
C(Country)  40911.874554   192.0  119.299063     0.0
Residual     4559.969449  2553.0         NaN     NaN

## Levene's Test for equal variance

In [164]:
lev_stat, p_value = stats.levene(life.loc[life['Status']=='Developing']['Life expectancy '],
                                 life.loc[life['Status']=='Developed']['Life expectancy '])

In [165]:
lev_stat

np.float64(nan)

## VIF

- Variance Inflation Factor
- VIF = 1 / 1 - R**2

r2 is the explained varience